/* Real propellants: liquid oxygen and ethanol. No DOM.

   Two kinds of data:

     Combustion   the products' characteristic velocity, temperature and
                  gas properties against mixture ratio and chamber
                  pressure, from NASA CEA (cea-lox-ethanol.js, generated by
                  tools/cea_tables.py). Bilinear in (ln Pc, MR) between the
                  table's points, clamped at its edges.
     Liquids      density, vapour pressure and heat capacity of what is in
                  the tanks — LOX as a cryogen, whose properties follow its
                  temperature, which the model tracks (biprop.js).

   The chamber model builds its gas from c* and γ: the products arrive with
   R·T = (η·c*·Γ(γ))². For that to land on CEA's chamber temperature, R here
   is not R_univ/M but the EFFECTIVE gas constant (c*·Γ(γ))²/Tc. The two
   agree to a per cent everywhere except very fuel-rich in the main table
   (MR ≤ 0.5), where CEA's equilibrium has solid carbon in it and a
   one-gas model cannot be exact; there the effective R keeps c* and Tc
   right and gives up the molecular weight. */

import { CEA_MAIN, CEA_GG } from './cea-lox-ethanol.js';

const Gam = g => Math.sqrt(g) * Math.pow(2 / (g + 1), (g + 1) / (2 * (g - 1)));
const BAR = 1e5;

/* Index and fraction of x in an ascending axis, clamped. */
function locate(xs, x) {
  if (!(x > xs[0])) return [0, 0];
  const n = xs.length - 1;
  if (x >= xs[n]) return [n - 1, 1];
  let i = 0;
  while (x > xs[i + 1]) i++;
  return [i, (x - xs[i]) / (xs[i + 1] - xs[i])];
}

/* A gas made from one CEA table: each property a function of (MR, P in Pa
   abs). P defaults to 20 bar (the main chambers' design neighbourhood). */
export function tableGas(T) {
  const lnP = T.pc.map(p => Math.log(p));
  const Reff = T.cstar.map((row, i) => row.map((cs, j) => (cs * Gam(T.gamma[i][j])) ** 2 / T.tc[i][j]));
  const look = grid => (MR, P = 20 * BAR) => {
    const [i, u] = locate(lnP, Math.log(Math.max(P, 1) / BAR));
    const [j, v] = locate(T.mr, MR);
    const a = grid[i], b = grid[i + 1];
    return (1 - u) * ((1 - v) * a[j] + v * a[j + 1]) + u * ((1 - v) * b[j] + v * b[j + 1]);
  };
  return {
    cstar: look(T.cstar), Tc: look(T.tc), gamma: look(T.gamma), R: look(Reff), M: look(T.mw),
    mrMin: T.mr[0], mrMax: T.mr[T.mr.length - 1],
  };
}

/* The main chambers: full equilibrium. */
export const GAS_MAIN = tableGas(CEA_MAIN);

/* A fuel-rich gas generator: the GG table (methane and soot suppressed) up
   to MR 1.2, the main table from 1.5 (a GG never runs there, but its start
   and shutdown pass through), blended between. */
const GG_ONLY = tableGas(CEA_GG);
const blend = k => (MR, P) => {
  if (MR <= 1.2) return GG_ONLY[k](MR, P);
  if (MR >= 1.5) return GAS_MAIN[k](MR, P);
  const w = (MR - 1.2) / 0.3;
  return (1 - w) * GG_ONLY[k](MR, P) + w * GAS_MAIN[k](MR, P);
};
export const GAS_GG = {
  cstar: blend('cstar'), Tc: blend('Tc'), gamma: blend('gamma'), R: blend('R'), M: blend('M'),
  mrMin: CEA_GG.mr[0], mrMax: CEA_MAIN.mr[CEA_MAIN.mr.length - 1],
};

/* ---- liquids ---------------------------------------------------------- */

const lin = (xs, ys) => x => { const [i, f] = locate(xs, x); return ys[i] + f * (ys[i + 1] - ys[i]); };
const antoineMmHgC = (A, B, C) => T => 133.322 * Math.pow(10, A - B / (C + Math.max(-30, Math.min(T - 273.15, 250))));

/* Water: Antoine, 1–100 °C (extrapolated beyond). */
const water = {
  name: 'Water (simulant)', rho: 998, cp: 4180,
  pvap: antoineMmHgC(8.07131, 1730.63, 233.426),
};

/* Liquid oxygen. Saturated-liquid density (NIST), vapour pressure from
   NIST's Antoine fit (54–154 K), and the critical point at 154.58 K,
   50.43 bar. Loaded at its normal boiling point, 90.19 K. */
const LOX_T = [54.4, 60, 70, 80, 90, 100, 110, 120, 130, 140, 154.58];
const LOX_RHO = [1306, 1282, 1237, 1190.5, 1141.9, 1087, 1028, 960, 880, 776, 436];
const LOX_TCRIT = 154.58, LOX_PCRIT = 50.43 * BAR;
const LOX = {
  name: 'LOX (liquid oxygen)', short: 'LOX', rho: 1141, cp: 1700, hfg: 213e3,
  cryo: true, Tload: 90.3, Tcrit: LOX_TCRIT, Pcrit: LOX_PCRIT,   // Tload: the fit's boiling point at one atmosphere
  rhoAt: lin(LOX_T, LOX_RHO),
  pvap: T => (T >= LOX_TCRIT ? LOX_PCRIT * (T / LOX_TCRIT) : BAR * Math.pow(10, 3.9523 - 340.024 / (Math.max(T, 55) - 4.144))),
  tsat: P => (P >= LOX_PCRIT ? LOX_TCRIT : 340.024 / (3.9523 - Math.log10(Math.max(P, 2e3) / BAR)) + 4.144),
};

/* Ethanol (anhydrous). Density linear in temperature about 20 °C; vapour
   pressure, Antoine (boils at 78.3 °C at one atmosphere). */
const ethanol = {
  name: 'Ethanol', short: 'ethanol', rho: 789, cp: 2440, hfg: 841e3,
  rhoAt: T => 789.3 - 0.86 * (T - 293.15),
  pvap: antoineMmHgC(8.20417, 1642.89, 230.3),
};

export const FLUIDS = { water, LOX, ethanol };

/* Stoichiometric mixture ratio, O2 / C2H5OH by mass: 3 × 32.00 / 46.07. */
export const MR_STOICH = 2.084;
