/* Reference entries. Concise, engineering-oriented, and honest about where
   the simulator simplifies. `see` links to related entries. */

export const CATEGORIES = [
  ['instr', 'Instrumentation & data'],
  ['fluid', 'Fluid systems'],
  ['ops', 'Test operations & safety'],
  ['perf', 'Performance'],
  ['comb', 'Bipropellant & combustion'],
];

export const GLOSSARY = [
  // ---- instrumentation
  { id: 'measured-vs-true', cat: 'instr', title: 'Measured state vs true state',
    body: ['The simulator knows the true pressure in every volume. You never see it. You see what each transducer reports, after its lag, offset, gain error, noise, quantisation and saturation — and, when something is wrong, after its fault.',
      'Every judgement a test engineer makes is about the true state, made from measurements. The discipline is to keep asking whether a measurement is physically consistent with the others. Two transducers on the same unflowing volume must agree; a thrust with no chamber pressure is impossible; a pressure that rises faster than any valve can fill the volume is an instrument, not the gas.'],
    see: ['pressure-transducer', 'zero-offset', 'uncertainty'] },
  { id: 'pressure-transducer', cat: 'instr', title: 'Pressure transducer (PT)',
    body: ['A diaphragm with strain gauges bonded to it, in a Wheatstone bridge. Pressure deflects the diaphragm, the bridge unbalances, an amplifier turns millivolts into a signal the DAQ digitises. Gauge transducers read relative to atmosphere (psig); absolute ones relative to vacuum (psia).',
      'What goes wrong: zero shift (temperature, overnight drift, mounting torque), span error, a disconnected or shorted cable (reads a rail or zero), a blocked sense port (reads a stale pressure), and overpressure damage. Response is usually well under a millisecond, but a long sense line in front of it can slow it dramatically.'],
    see: ['zero-offset', 'calibration', 'sample-rate'] },
  { id: 'thermocouple', cat: 'instr', title: 'Thermocouple (TC)',
    body: ['Two dissimilar metals joined at a junction produce a voltage that depends on the temperature difference between that junction and the reference (cold) junction at the DAQ. Type K (chromel–alumel) covers −200 to 1250 °C.',
      'A TC reads the temperature of its own junction, which lags the gas or wall it is in: a sheathed probe takes seconds, an exposed fine junction tens of milliseconds. Errors come from the cold-junction compensation, conduction along the sheath, and radiation. An open thermocouple usually reads off-scale — a sudden jump to an impossible temperature is the wire, not the hardware.'],
    see: ['measured-vs-true'] },
  { id: 'load-cell', cat: 'instr', title: 'Load cell and thrust stand',
    body: ['A strain-gauged metal element in the load path between the thrust stand\'s moving platform and ground. The platform rides on flexures, which are stiff along every axis but the thrust axis.',
      'The stand is a spring-mass system: a step in thrust makes it ring at its natural frequency (here ≈ 120 Hz) before settling. Peak readings during the start transient include that ringing — they are not peak thrust. Feed lines crossing onto the stand add stiffness and pressure tare. A test stand is calibrated in place, by hanging known weights or with a reference load cell.'],
    see: ['pressure-tare', 'shunt-calibration', 'thrust-transient'] },
  { id: 'daq', cat: 'instr', title: 'Data acquisition system (DAQ)',
    body: ['Signal conditioning (bridge excitation, amplification, filtering), analogue-to-digital conversion, timing and storage for every channel. It also produces calculated channels (mass flow from pressure, for example) and usually runs the redline checks.',
      'The DAQ is where "measured" is made. Its configuration — sample rate, filter, calibration factors, which channels are in the file — is part of the test configuration and is verified like any valve.'],
    see: ['sample-rate', 'anti-aliasing', 'redline'] },
  { id: 'sample-rate', cat: 'instr', title: 'Sample rate',
    body: ['Samples per second per channel. You cannot see anything faster than about a fifth of it in practice (the Nyquist limit is a half, but a sine sampled twice per cycle is unrecognisable). A 3 ms valve opening needs at least 1–2 kHz; a tank blowing down over minutes is fine at 10 Hz.',
      'Faster sampling also admits more noise bandwidth, and more data. Choose the rate for the fastest thing you need to see.'],
    see: ['anti-aliasing', 'daq'] },
  { id: 'anti-aliasing', cat: 'instr', title: 'Anti-aliasing filter',
    body: ['A low-pass filter ahead of the digitiser that removes content above half the sample rate. Without it, a 120 Hz thrust-stand ring sampled at 100 Hz would appear as a slow 20 Hz wobble that does not exist. With it, the ring simply disappears — which is also a loss of information. The simulator places the filter corner at 35 % of the sample rate.'],
    see: ['sample-rate'] },
  { id: 'zero-offset', cat: 'instr', title: 'Zero offset and sensor bias',
    body: ['The reading a sensor gives when the true value is zero. Every transducer has one and it drifts. Zeroing (taring) subtracts it — correctly only if the true value really is zero at that moment.',
      'Bias is any constant error, zero-related or not. A biased channel looks perfectly healthy: steady, low noise, plausible. It is found by comparison — against a redundant sensor, against a second transducer on the same volume, against physics (no pressure drop without flow).'],
    see: ['calibration', 'measured-vs-true'] },
  { id: 'calibration', cat: 'instr', title: 'Calibration',
    body: ['Establishing the relationship between a sensor\'s output and the true quantity, against a traceable reference: a deadweight tester or reference gauge for PTs, a calibrated bath for TCs, known weights or a reference load cell for a thrust stand. A calibration has a date, a range and an uncertainty.',
      'Zeroing is not calibration: it fixes the offset, not the slope. A shunt calibration is not calibration either: it checks the electronics, not the sensor.'],
    see: ['shunt-calibration', 'uncertainty'] },
  { id: 'shunt-calibration', cat: 'instr', title: 'Shunt calibration',
    body: ['A precision resistor switched across one arm of a strain-gauge bridge produces a known electrical imbalance, equivalent to a stated load (here 25.00 N). If the channel reads that value, the excitation, amplifier gain and DAQ scaling are right. It says nothing about whether the load cell itself, or its mounting, still has its original sensitivity.'],
    see: ['load-cell', 'calibration'] },
  { id: 'pressure-tare', cat: 'instr', title: 'Pressure tare',
    body: ['Pressurising the feed line that crosses onto a thrust stand makes the line push on the stand, and the load cell reads a force with nothing firing. A zero taken vented is not the zero you fire from. Practice: tare with the system at test pressure just before firing, and in analysis subtract a pre-fire baseline from the recorded data.'],
    see: ['load-cell'] },
  { id: 'uncertainty', cat: 'instr', title: 'Measurement uncertainty',
    body: ['The range within which the true value is believed to lie. It combines calibration uncertainty, noise (reduced by averaging), resolution, drift since calibration, and installation effects. A thrust of 6.21 N ± 0.05 N and 6.21 N ± 0.5 N are different results. Comparing two runs, or a run with a prediction, means asking whether the difference is larger than the uncertainty of both.'],
    see: ['calibration'] },

  // ---- fluid systems
  { id: 'regulator', cat: 'fluid', title: 'Pressure regulator',
    body: ['Reduces a high, falling supply pressure to a lower, steady outlet pressure. A poppet is pushed open by the loading (a spring, or a dome pressurised by a controller) and pushed closed by outlet pressure acting on a diaphragm; it settles where the two balance.',
      'Real regulators droop (outlet falls with flow), lock up slightly above set at zero flow, creep up as the supply falls (supply-pressure effect), and drop out when the supply falls close to the outlet pressure. A non-relieving regulator can only add gas downstream: turn its setpoint down and the outlet pressure stays where it was until something downstream flows or vents. A self-relieving one vents the excess through its bonnet. Failures: seat leakage (outlet creeps up with no flow — the relief valve is the backstop), sticking, and set-point error.'],
    see: ['droop', 'lock-up', 'relief-valve'] },
  { id: 'droop', cat: 'fluid', title: 'Regulator droop',
    body: ['The fall in regulator outlet pressure as flow increases. The poppet only opens because the outlet has fallen below the loading; more flow needs more opening, so more fall. Watch PT-201 at the moment the fire valve opens: it steps down a few psi and stays there. Excessive droop means an undersized or failing regulator — or a supply near dropout.'],
    see: ['regulator', 'lock-up'] },
  { id: 'lock-up', cat: 'fluid', title: 'Lock-up',
    body: ['The outlet pressure at which a regulator closes completely with no flow — slightly above its flowing set pressure. When flow stops, outlet pressure rises to lock-up and holds. If it keeps rising, the seat is leaking.'],
    see: ['regulator'] },
  { id: 'isolation-valve', cat: 'fluid', title: 'Isolation valve',
    body: ['A valve whose job is to be fully open or fully closed, separating one part of a system from another: the stored gas from the test system, a test section from the facility. Remote isolation valves have limit switches that report the open and closed positions, and a defined fail position.'],
    see: ['fail-safe', 'trapped-volume'] },
  { id: 'solenoid-valve', cat: 'fluid', title: 'Solenoid valve',
    body: ['A valve opened by the magnetic pull of a coil on an iron armature. Current in an inductive coil rises over milliseconds; the armature moves only once the pull beats the spring and the pressure load on the seat, so opening delay grows with inlet pressure. The armature\'s motion induces a back-EMF that puts a dip in the coil current — the standard way to see, from the data, that the valve actually stroked.'],
    see: ['thrust-transient', 'impulse-bit'] },
  { id: 'relief-valve', cat: 'fluid', title: 'Relief valve',
    body: ['A spring-loaded valve that opens when pressure exceeds its set point and closes again once pressure has fallen by its blowdown. It protects everything downstream of a regulator from a regulator failure. Set above the maximum expected operating pressure and below the maximum allowable working pressure of what it protects. A relief valve that lifts during a test is telling you something upstream has failed.'],
    see: ['meop', 'regulator'] },
  { id: 'vent', cat: 'fluid', title: 'Vent',
    body: ['A controlled path to atmosphere (via a vent stack) for removing pressure. Vent valves are normally open: their de-energised, fail-safe state is venting, so they must be commanded closed to pressurise. A system is only "vented" when every section has been vented through its own path and verified at zero.'],
    see: ['trapped-volume', 'fail-safe', 'bleed'] },
  { id: 'bleed', cat: 'fluid', title: 'Bleed',
    body: ['A small, deliberate, controlled release of pressure — from a trapped section, a gauge line, or a line being prepared for disconnection. A bleed is slow on purpose. In cryogenic systems, "bleed" also means flowing propellant to chill lines before a test.'],
    see: ['vent', 'trapped-volume'] },
  { id: 'trapped-volume', cat: 'fluid', title: 'Trapped volume',
    body: ['Any section of a system that can be isolated with pressure in it — between two closed valves, or between a closed valve and a shut regulator. Venting the system around it does not vent it. On TS-1, the gas between IV-101 and a shut PR-101 stays at bottle pressure until VV-101 is opened; the pipe between the bottle valve and IV-101 stays pressurised after the bottle is closed. Finding trapped volumes is a design-review question and a safing-procedure question.'],
    see: ['vent', 'bleed'] },
  { id: 'pressure-drop', cat: 'fluid', title: 'Pressure drop',
    body: ['Pressure lost across a restriction — a valve, filter, orifice, bend or length of line — because gas is flowing through it. It grows roughly with flow squared and is zero with no flow. That is why a partly blocked filter or a restricted line is invisible in a static pressure check and obvious during a firing: compare the transducers either side while the gas moves.'],
    see: ['choked-flow'] },
  { id: 'choked-flow', cat: 'fluid', title: 'Choked flow',
    body: ['When the downstream-to-upstream pressure ratio across a restriction falls below the critical ratio (0.528 for nitrogen), the gas reaches sonic speed at the narrowest point and the mass flow stops depending on the downstream pressure: ṁ = Cd·A·P₀·Γ/√(R·T₀). A nozzle throat runs choked, which makes mass flow directly proportional to chamber pressure — the basis of the calculated mass-flow channel.'],
    see: ['characteristic-velocity', 'nozzle-expansion'] },
  { id: 'blowdown', cat: 'fluid', title: 'Blowdown',
    body: ['A tank supplying gas without being refilled loses pressure as it empties, and the gas left inside cools because it has done work expanding (about 1.5 K per percent of mass for nitrogen, adiabatically). The walls warm it back slowly. Blowdown sets how long a stand can run and, below the regulator\'s dropout pressure, how long it can run at constant pressure.'],
    see: ['regulator'] },

  { id: 'coriolis-flowmeter', cat: 'instr', title: 'Mass flowmeter (Coriolis)',
    body: ['Gas flows through a vibrating tube; the Coriolis force twists the tube in proportion to the mass flow, and the twist is measured directly — no assumption about density, temperature or throat area. That makes it the reference against which a calculated flow is checked.',
      'Its weakness is speed. The output is heavily filtered (FT-201 responds in ~60 ms), so it cannot follow a start transient or a short pulse, and during a start it reads the line filling, not the thruster. Use it in steady state.'],
    see: ['characteristic-velocity', 'specific-impulse'] },

  // ---- operations & safety
  { id: 'redline', cat: 'ops', title: 'Redline',
    body: ['A limit on a measured value beyond which the test is aborted — automatically or by the operator. Each redline has a channel, a threshold, a time window in which it is armed (a low chamber-pressure redline means nothing before the valve opens), and a persistence (how long the value must be over the limit, so that a single noise spike does not abort a test).',
      'A redline acts on a measurement. A failed transducer can trip one; a real failure can hide behind a healthy-looking sensor. Critical parameters are often voted between redundant sensors for exactly this reason.'],
    see: ['abort', 'interlock', 'measured-vs-true'] },
  { id: 'interlock', cat: 'ops', title: 'Interlock',
    body: ['A condition that must be true before an action is allowed: the fire circuit cannot be armed with the cell door open; the fire valve cannot open unless armed. Hard interlocks are wired into hardware and cannot be bypassed from the console. Softer rules — warnings, procedural holds — rely on people. The simulator uses all three, and in independent mode many rules become consequences instead of blocks.'],
    see: ['redline', 'go-no-go'] },
  { id: 'fail-safe', cat: 'ops', title: 'Fail-safe position',
    body: ['Where a valve goes when it loses power or actuating air. Supply isolation fails closed; vents fail open; the fire valve fails closed. A system designed this way moves toward safe when anything is lost — which is also why vents must be actively held closed to pressurise.'],
    see: ['vent', 'isolation-valve'] },
  { id: 'purge', cat: 'ops', title: 'Purge',
    body: ['Flowing an inert gas (usually nitrogen or helium) through a line or chamber to remove air, moisture or propellant, or to keep hot gas and propellant out of an injector. Bipropellant engines are purged before start, often during start and shutdown, and after shutdown to clear residual propellant. A cold-gas nitrogen stand is its own purge gas and needs none.'],
    see: ['residual-propellant'] },
  { id: 'proof-test', cat: 'ops', title: 'Proof test',
    body: ['A pressure test of hardware to a level above its maximum expected operating pressure (commonly 1.5× MEOP for ground hardware), done remotely before the hardware is used, to demonstrate it holds with margin. It is done once per configuration and repeated after modification — not before every test.'],
    see: ['meop', 'leak-check'] },
  { id: 'meop', cat: 'ops', title: 'MEOP, MAWP and margins',
    body: ['Maximum expected operating pressure (MEOP) is the highest pressure the system should see in operation, including transients. Maximum allowable working pressure (MAWP) is what the weakest component is rated for. Relief is set between them. On TS-1\'s low-pressure side: MEOP 200 psig, relief 250 psig, MAWP 300 psig.'],
    see: ['relief-valve', 'proof-test'] },
  { id: 'leak-check', cat: 'ops', title: 'Leak check',
    body: ['Pressurise a section, isolate it, and watch the pressure. A falling pressure in an isolated volume is a leak — or a temperature change, so wait for the gas to settle and judge the slope, not a single reading. A regulator must be shut during the check: a regulating regulator replaces whatever leaks out and hides it. Leak checks are done first at a pressure people may be near, then (remotely) at test pressure; a leak located with snoop liquid is fixed at low pressure, never tightened under pressure.'],
    see: ['trapped-volume'] },
  { id: 'characterisation', cat: 'ops', title: 'Characterisation and test series',
    body: ['A single firing answers "what did it do?"; a characterisation answers "how does it behave?" by varying one thing — pressure, pulse width — across a planned test matrix while holding everything else fixed, then fitting the result. The fit is the product: a slope and an intercept with uncertainties, and what they say about the hardware.',
      'A series is normally run under one go/no-go poll for the approved matrix. Moving between approved points does not need a new poll; anything outside the matrix — a valve, the cell, a technician task — does. And every point starts from the same verified static condition as the first.'],
    see: ['thrust-coefficient', 'impulse-bit', 'go-no-go'] },
  { id: 'fault-isolation', cat: 'ops', title: 'Fault isolation and root cause',
    body: ['First decide whether the anomaly is in the system or in the instrument. A real change in the system shows on every channel that physics connects to it — a low chamber pressure means low thrust and low flow too. A sensor fault shows on one channel alone, and the others disagree with it. Redundant or independent measurements (a second transducer, a flowmeter against a calculated flow, a shunt calibration, a reference gauge) are how the two are told apart.',
      'Then locate before naming: "the pressure drop is between PT-201 and PT-301, and only with flow" narrows the list to what lies between two taps. Only then pick the inspection whose result would change your mind — the cheapest first. An inspection that finds nothing is evidence: it removes a suspect. A root cause names the component, the failure mode and the evidence, and says what should be done.'],
    see: ['abort', 'shunt-calibration', 'coriolis-flowmeter'] },
  { id: 'data-validity', cat: 'ops', title: 'Data validity and the test report',
    body: ['A number in a test report will be used by someone who was not there: to size a propellant load, to accept hardware, to change a design. Before it is reported, the test conductor decides whether it represents the article. Data are invalid when the stand was not as specified (a restriction, a wrong part, a regulator that could not hold its setpoint) or when an instrument in the chain was wrong (a bias, a bad calibration, a load path that bypasses the load cell). Invalid data are not deleted — they are labelled, explained, and kept, because they are evidence of what went wrong.',
      'Reduced correctly, bad data still produce clean-looking numbers. That is the danger: a reduction checks arithmetic, not truth. The checks that catch it are comparisons — against the prediction, against an independent measurement, against the last good run — and the conductor\'s willingness to write "invalid" on a test that cost a day.'],
    see: ['fault-isolation', 'characterisation', 'shunt-calibration'] },
  { id: 'go-no-go', cat: 'ops', title: 'Go / no-go poll',
    body: ['Before arming, the test conductor calls each station; each answers GO or NO-GO from its own data. The poll\'s value is the NO-GO: it is the last point at which a problem costs only time. A good poll is not a ritual — each station states the facts it is basing its call on, and any change to the configuration afterwards invalidates it.'],
    see: ['interlock', 'abort'] },
  { id: 'abort', cat: 'ops', title: 'Abort',
    body: ['Terminating a test by driving the system to a safe configuration as fast as is safe: stop the flow, isolate the supply, remove the loading, vent. Abort sequences are written in advance and executed by the controller, not improvised. After an abort, the question is always the same: was it a real system problem or an instrumentation problem? The answer determines whether the hardware can be retested.'],
    see: ['redline', 'measured-vs-true'] },

  // ---- performance
  { id: 'chamber-pressure', cat: 'perf', title: 'Chamber pressure',
    body: ['The stagnation pressure upstream of the nozzle throat. For a choked throat it sets the mass flow (ṁ = Pc·At/c*) and, with the thrust coefficient, the thrust (F = Cf·Pc·At). It is the single most informative measurement on a rocket engine: most faults show up as a chamber pressure that does not match the feed pressures that should produce it.'],
    see: ['thrust-coefficient', 'characteristic-velocity'] },
  { id: 'thrust-coefficient', cat: 'perf', title: 'Thrust coefficient (Cf)',
    body: ['Cf = F / (Pc·At): how well the nozzle turns chamber pressure into thrust. It depends on the expansion ratio, the gas, the ambient pressure (the (Pe − Pa)·Ae term), divergence loss, and whether the flow separates. Plotting F against Pc gives a straight line with a negative intercept of about −Pa·Ae — its slope and intercept are nozzle diagnostics.'],
    see: ['nozzle-expansion', 'chamber-pressure'] },
  { id: 'nozzle-expansion', cat: 'perf', title: 'Over- and under-expansion, separation',
    body: ['A nozzle expands gas to an exit pressure fixed by its area ratio and chamber pressure. If that is above ambient the nozzle is under-expanded (thrust left on the table); below ambient, over-expanded (the pressure term is negative). Far enough below — roughly 40 % of ambient — the flow separates from the wall. CGT-1\'s ratio of 2 is matched near 150 psia at sea level; at low chamber pressure it runs separated.'],
    see: ['thrust-coefficient'] },
  { id: 'characteristic-velocity', cat: 'perf', title: 'Characteristic velocity (c*)',
    body: ['c* = Pc·At / ṁ, a measure of how much chamber pressure a given mass flow produces through a given throat. For cold gas it depends only on the gas and its temperature (≈ 430 m/s for room-temperature nitrogen). For a combustion chamber it measures combustion efficiency. An apparent change in c* is a clue: either the gas, the throat, or a measurement changed.'],
    see: ['chamber-pressure', 'specific-impulse'] },
  { id: 'specific-impulse', cat: 'perf', title: 'Specific impulse (Isp)',
    body: ['Impulse per unit weight of propellant: Isp = F / (ṁ·g₀), in seconds. Nitrogen cold gas gives about 73 s in vacuum and roughly 55 s from this sea-level nozzle. Measured Isp is only as good as the thrust AND the mass flow; if mass flow is calculated from chamber pressure and an assumed throat, an eroded throat corrupts Isp while every channel looks healthy.'],
    see: ['total-impulse', 'characteristic-velocity'] },
  { id: 'total-impulse', cat: 'perf', title: 'Total impulse',
    body: ['The integral of thrust over time, ∫F dt, in N·s. Integrate baseline-corrected thrust over the whole firing including the start and shutdown transients, and check the baseline: a 0.3 N zero error integrated over 3 s is a 5 % error in a 6 N·s burn.'],
    see: ['impulse-bit', 'pressure-tare'] },
  { id: 'impulse-bit', cat: 'perf', title: 'Impulse bit',
    body: ['The total impulse delivered by one short pulse. For attitude-control thrusters it is the figure that matters: the smallest repeatable impulse bit sets how finely a spacecraft can be pointed. For very short pulses the valve never fully opens and the chamber never reaches steady state, so the impulse bit is dominated by valve timing — and its repeatability by valve-to-valve variation.'],
    see: ['solenoid-valve', 'thrust-transient'] },
  { id: 'thrust-transient', cat: 'perf', title: 'Thrust transient',
    body: ['The start and stop of thrust. At start: electrical delay in the valve coil, armature travel, chamber filling, and the thrust stand\'s own response (which rings). At stop: coil current decay to drop-out, armature return, and chamber emptying through the throat. The measured thrust transient is always the thruster convolved with the stand — read peaks with suspicion.'],
    see: ['pressure-transient', 'load-cell'] },
  { id: 'pressure-transient', cat: 'perf', title: 'Pressure transient',
    body: ['How pressures move when something changes: a chamber filling in milliseconds, a regulator outlet dipping and recovering as flow starts (droop and response), a feed line surging when a valve slams. Characterising transients — rise time, overshoot, settling — tells you about volumes, valve speeds and control stability that steady-state data cannot.'],
    see: ['thrust-transient', 'droop'] },

  // ---- biprop (Phase 6–7 content; definitions now)
  { id: 'injector-pressure-drop', cat: 'comb', title: 'Injector pressure drop',
    body: ['The difference between manifold pressure and chamber pressure across an injector, typically 15–25 % of chamber pressure. It sets the propellant flow (ṁ ≈ Cd·A·√(2ρΔP)) and isolates the feed system from chamber pressure oscillations: too little ΔP and the feed couples to the chamber (chugging); too much and the feed system must be heavier.'],
    see: ['combustion-instability', 'mixture-ratio'] },
  { id: 'mixture-ratio', cat: 'comb', title: 'Mixture ratio',
    body: ['Oxidiser mass flow divided by fuel mass flow (O/F). It sets combustion temperature and c*, and so performance and heat load. Measured from two flowmeters, or inferred from injector pressure drops; an error in either flow channel is an error in mixture ratio.'],
    see: ['injector-pressure-drop'] },
  { id: 'hard-start', cat: 'comb', title: 'Hard start',
    body: ['An ignition that happens after too much propellant has accumulated in the chamber, so it burns almost at once and produces a pressure spike far above normal chamber pressure. Causes: late ignition, a valve leading the igniter, a failed igniter. Prevention: ignition confirmation before main-valve opening, and careful valve sequencing.'],
    see: ['combustion-instability'] },
  { id: 'combustion-instability', cat: 'comb', title: 'Combustion instability',
    body: ['Self-sustaining pressure oscillations in a combustion chamber: low-frequency "chugging" coupled to the feed system, or high-frequency acoustic modes of the chamber that can destroy an injector in milliseconds. Seen as growing oscillation on a high-response chamber-pressure channel — which is why that channel is sampled fast and why an oscillation redline exists.'],
    see: ['injector-pressure-drop'] },
  { id: 'residual-propellant', cat: 'comb', title: 'Residual propellant',
    body: ['Propellant left in manifolds and injector passages after main-valve closure. It can burn or dribble after shutdown (an afterburn visible on chamber pressure) and must be purged before the hardware is approached.'],
    see: ['purge'] },
];
