/* Reference entries. Concise, engineering-oriented, and honest about where
   the simulator simplifies. `see` links to related entries. */

export const CATEGORIES = [
  ['instr', 'Instrumentation & data'],
  ['fluid', 'Fluid systems'],
  ['ops', 'Test operations & safety'],
  ['perf', 'Performance'],
  ['comb', 'Bipropellant & combustion'],
  ['turbo', 'Turbomachinery'],
];

export const GLOSSARY = [
  // ---- instrumentation
  { id: 'measured-vs-true', cat: 'instr', title: 'Measured state vs true state',
    body: ['The simulator knows the true pressure in every volume. You never see it. You see what each transducer reports, after its lag, offset, gain error, noise, quantisation and saturation — and, when something is wrong, after its fault.',
      'Every judgement a test engineer makes is about the true state, made from measurements. The discipline is to keep asking whether a measurement is physically consistent with the others. Two transducers on the same unflowing volume must agree; a thrust with no chamber pressure is impossible; a pressure that rises faster than any valve can fill the volume is an instrument, not the gas.'],
    see: ['pressure-transducer', 'zero-offset', 'uncertainty'] },
  { id: 'pressure-transducer', cat: 'instr', title: 'Pressure transducer (PT)',
    body: ['A diaphragm with strain gauges bonded to it, in a Wheatstone bridge. Pressure deflects the diaphragm, the bridge unbalances, an amplifier turns millivolts into a signal the DAQ digitises. Gauge transducers read relative to atmosphere (psig); absolute ones relative to vacuum (psia).',
      'What goes wrong: zero shift (temperature, overnight drift, mounting torque), span error, a disconnected or shorted cable (reads a rail or zero), a blocked sense port (reads a stale pressure), and overpressure damage. Response is usually well under a millisecond, but a long sense line in front of it can slow it dramatically.'],
    see: ['zero-offset', 'calibration', 'sample-rate'] },
  { id: 'thermocouple', cat: 'instr', title: 'Thermocouple (TC)',
    body: ['Two dissimilar metals joined at a junction produce a voltage that depends on the temperature difference between that junction and the reference (cold) junction at the DAQ. Type K (chromel–alumel) covers −200 to 1250 °C.',
      'A TC reads the temperature of its own junction, which lags the gas or wall it is in: a sheathed probe takes seconds, an exposed fine junction tens of milliseconds. Errors come from the cold-junction compensation, conduction along the sheath, and radiation. An open thermocouple usually reads off-scale — a sudden jump to an impossible temperature is the wire, not the hardware.'],
    see: ['measured-vs-true'] },
  { id: 'load-cell', cat: 'instr', title: 'Load cell and thrust stand',
    body: ['A strain-gauged metal element in the load path between the thrust stand\'s moving platform and ground. The platform rides on flexures, which are stiff along every axis but the thrust axis.',
      'The stand is a spring-mass system: a step in thrust makes it ring at its natural frequency (here ≈ 120 Hz) before settling. Peak readings during the start transient include that ringing — they are not peak thrust. Feed lines crossing onto the stand add stiffness and pressure tare. A test stand is calibrated in place, by hanging known weights or with a reference load cell.'],
    see: ['pressure-tare', 'shunt-calibration', 'thrust-transient'] },
  { id: 'daq', cat: 'instr', title: 'Data acquisition system (DAQ)',
    body: ['Signal conditioning (bridge excitation, amplification, filtering), analogue-to-digital conversion, timing and storage for every channel. It also produces calculated channels (mass flow from pressure, for example) and usually runs the redline checks.',
      'The DAQ is where "measured" is made. Its configuration — sample rate, filter, calibration factors, which channels are in the file — is part of the test configuration and is verified like any valve.'],
    see: ['sample-rate', 'anti-aliasing', 'redline'] },
  { id: 'sample-rate', cat: 'instr', title: 'Sample rate',
    body: ['Samples per second per channel. You cannot see anything faster than about a fifth of it in practice (the Nyquist limit is a half, but a sine sampled twice per cycle is unrecognisable). A 3 ms valve opening needs at least 1–2 kHz; a tank blowing down over minutes is fine at 10 Hz.',
      'Faster sampling also admits more noise bandwidth, and more data. Choose the rate for the fastest thing you need to see.'],
    see: ['anti-aliasing', 'daq'] },
  { id: 'anti-aliasing', cat: 'instr', title: 'Anti-aliasing filter',
    body: ['A low-pass filter ahead of the digitiser that removes content above half the sample rate. Without it, a 120 Hz thrust-stand ring sampled at 100 Hz would appear as a slow 20 Hz wobble that does not exist. With it, the ring simply disappears — which is also a loss of information. The simulator places the filter corner at 35 % of the sample rate.'],
    see: ['sample-rate'] },
  { id: 'zero-offset', cat: 'instr', title: 'Zero offset and sensor bias',
    body: ['The reading a sensor gives when the true value is zero. Every transducer has one and it drifts. Zeroing (taring) subtracts it — correctly only if the true value really is zero at that moment.',
      'Bias is any constant error, zero-related or not. A biased channel looks perfectly healthy: steady, low noise, plausible. It is found by comparison — against a redundant sensor, against a second transducer on the same volume, against physics (no pressure drop without flow).'],
    see: ['calibration', 'measured-vs-true'] },
  { id: 'calibration', cat: 'instr', title: 'Calibration',
    body: ['Establishing the relationship between a sensor\'s output and the true quantity, against a traceable reference: a deadweight tester or reference gauge for PTs, a calibrated bath for TCs, known weights or a reference load cell for a thrust stand. A calibration has a date, a range and an uncertainty.',
      'Zeroing is not calibration: it fixes the offset, not the slope. A shunt calibration is not calibration either: it checks the electronics, not the sensor.'],
    see: ['shunt-calibration', 'uncertainty'] },
  { id: 'shunt-calibration', cat: 'instr', title: 'Shunt calibration',
    body: ['A precision resistor switched across one arm of a strain-gauge bridge produces a known electrical imbalance, equivalent to a stated load (here 25.00 N). If the channel reads that value, the excitation, amplifier gain and DAQ scaling are right. It says nothing about whether the load cell itself, or its mounting, still has its original sensitivity.'],
    see: ['load-cell', 'calibration'] },
  { id: 'pressure-tare', cat: 'instr', title: 'Pressure tare',
    body: ['Pressurising the feed line that crosses onto a thrust stand makes the line push on the stand, and the load cell reads a force with nothing firing. A zero taken vented is not the zero you fire from. Practice: tare with the system at test pressure just before firing, and in analysis subtract a pre-fire baseline from the recorded data.'],
    see: ['load-cell'] },
  { id: 'uncertainty', cat: 'instr', title: 'Measurement uncertainty',
    body: ['The range within which the true value is believed to lie. It combines calibration uncertainty, noise (reduced by averaging), resolution, drift since calibration, and installation effects. A thrust of 6.21 N ± 0.05 N and 6.21 N ± 0.5 N are different results. Comparing two runs, or a run with a prediction, means asking whether the difference is larger than the uncertainty of both.'],
    see: ['calibration'] },

  // ---- fluid systems
  { id: 'regulator', cat: 'fluid', title: 'Pressure regulator',
    body: ['Reduces a high, falling supply pressure to a lower, steady outlet pressure. A poppet is pushed open by the loading (a spring, or a dome pressurised by a controller) and pushed closed by outlet pressure acting on a diaphragm; it settles where the two balance.',
      'Real regulators droop (outlet falls with flow), lock up slightly above set at zero flow, creep up as the supply falls (supply-pressure effect), and drop out when the supply falls close to the outlet pressure. A non-relieving regulator can only add gas downstream: turn its setpoint down and the outlet pressure stays where it was until something downstream flows or vents. A self-relieving one vents the excess through its bonnet. Failures: seat leakage (outlet creeps up with no flow — the relief valve is the backstop), sticking, and set-point error.'],
    see: ['droop', 'lock-up', 'relief-valve'] },
  { id: 'droop', cat: 'fluid', title: 'Regulator droop',
    body: ['The fall in regulator outlet pressure as flow increases. The poppet only opens because the outlet has fallen below the loading; more flow needs more opening, so more fall. Watch PT-201 at the moment the fire valve opens: it steps down a few psi and stays there. Excessive droop means an undersized or failing regulator — or a supply near dropout.'],
    see: ['regulator', 'lock-up'] },
  { id: 'lock-up', cat: 'fluid', title: 'Lock-up',
    body: ['The outlet pressure at which a regulator closes completely with no flow — slightly above its flowing set pressure. When flow stops, outlet pressure rises to lock-up and holds. If it keeps rising, the seat is leaking.'],
    see: ['regulator'] },
  { id: 'isolation-valve', cat: 'fluid', title: 'Isolation valve',
    body: ['A valve whose job is to be fully open or fully closed, separating one part of a system from another: the stored gas from the test system, a test section from the facility. Remote isolation valves have limit switches that report the open and closed positions, and a defined fail position.'],
    see: ['fail-safe', 'trapped-volume'] },
  { id: 'solenoid-valve', cat: 'fluid', title: 'Solenoid valve',
    body: ['A valve opened by the magnetic pull of a coil on an iron armature. Current in an inductive coil rises over milliseconds; the armature moves only once the pull beats the spring and the pressure load on the seat, so opening delay grows with inlet pressure. The armature\'s motion induces a back-EMF that puts a dip in the coil current — the standard way to see, from the data, that the valve actually stroked.'],
    see: ['thrust-transient', 'impulse-bit'] },
  { id: 'relief-valve', cat: 'fluid', title: 'Relief valve',
    body: ['A spring-loaded valve that opens when pressure exceeds its set point and closes again once pressure has fallen by its blowdown. It protects everything downstream of a regulator from a regulator failure. Set above the maximum expected operating pressure and below the maximum allowable working pressure of what it protects. A relief valve that lifts during a test is telling you something upstream has failed.'],
    see: ['meop', 'regulator'] },
  { id: 'vent', cat: 'fluid', title: 'Vent',
    body: ['A controlled path to atmosphere (via a vent stack) for removing pressure. Vent valves are normally open: their de-energised, fail-safe state is venting, so they must be commanded closed to pressurise. A system is only "vented" when every section has been vented through its own path and verified at zero.'],
    see: ['trapped-volume', 'fail-safe', 'bleed'] },
  { id: 'bleed', cat: 'fluid', title: 'Bleed',
    body: ['A small, deliberate, controlled release of pressure — from a trapped section, a gauge line, or a line being prepared for disconnection. A bleed is slow on purpose. In cryogenic systems, "bleed" also means flowing propellant to chill lines before a test.'],
    see: ['vent', 'trapped-volume'] },
  { id: 'trapped-volume', cat: 'fluid', title: 'Trapped volume',
    body: ['Any section of a system that can be isolated with pressure in it — between two closed valves, or between a closed valve and a shut regulator. Venting the system around it does not vent it. On TS-1, the gas between IV-101 and a shut PR-101 stays at bottle pressure until VV-101 is opened; the pipe between the bottle valve and IV-101 stays pressurised after the bottle is closed. Finding trapped volumes is a design-review question and a safing-procedure question.'],
    see: ['vent', 'bleed'] },
  { id: 'pressure-drop', cat: 'fluid', title: 'Pressure drop',
    body: ['Pressure lost across a restriction — a valve, filter, orifice, bend or length of line — because gas is flowing through it. It grows roughly with flow squared and is zero with no flow. That is why a partly blocked filter or a restricted line is invisible in a static pressure check and obvious during a firing: compare the transducers either side while the gas moves.'],
    see: ['choked-flow'] },
  { id: 'choked-flow', cat: 'fluid', title: 'Choked flow',
    body: ['When the downstream-to-upstream pressure ratio across a restriction falls below the critical ratio (0.528 for nitrogen), the gas reaches sonic speed at the narrowest point and the mass flow stops depending on the downstream pressure: ṁ = Cd·A·P₀·Γ/√(R·T₀). A nozzle throat runs choked, which makes mass flow directly proportional to chamber pressure — the basis of the calculated mass-flow channel.'],
    see: ['characteristic-velocity', 'nozzle-expansion'] },
  { id: 'blowdown', cat: 'fluid', title: 'Blowdown',
    body: ['A tank supplying gas without being refilled loses pressure as it empties, and the gas left inside cools because it has done work expanding (about 1.5 K per percent of mass for nitrogen, adiabatically). The walls warm it back slowly. Blowdown sets how long a stand can run and, below the regulator\'s dropout pressure, how long it can run at constant pressure.'],
    see: ['regulator'] },

  { id: 'coriolis-flowmeter', cat: 'instr', title: 'Mass flowmeter (Coriolis)',
    body: ['Gas flows through a vibrating tube; the Coriolis force twists the tube in proportion to the mass flow, and the twist is measured directly — no assumption about density, temperature or throat area. That makes it the reference against which a calculated flow is checked.',
      'Its weakness is speed. The output is heavily filtered (FT-201 responds in ~60 ms), so it cannot follow a start transient or a short pulse, and during a start it reads the line filling, not the thruster. Use it in steady state.'],
    see: ['characteristic-velocity', 'specific-impulse'] },

  // ---- operations & safety
  { id: 'redline', cat: 'ops', title: 'Redline',
    body: ['A limit on a measured value beyond which the test is aborted — automatically or by the operator. Each redline has a channel, a threshold, a time window in which it is armed (a low chamber-pressure redline means nothing before the valve opens), and a persistence (how long the value must be over the limit, so that a single noise spike does not abort a test).',
      'A redline acts on a measurement. A failed transducer can trip one; a real failure can hide behind a healthy-looking sensor. Critical parameters are often voted between redundant sensors for exactly this reason.'],
    see: ['abort', 'interlock', 'measured-vs-true'] },
  { id: 'interlock', cat: 'ops', title: 'Interlock',
    body: ['A condition that must be true before an action is allowed: the fire circuit cannot be armed with the cell door open; the fire valve cannot open unless armed. Hard interlocks are wired into hardware and cannot be bypassed from the console. Softer rules — warnings, procedural holds — rely on people. The simulator uses all three, and in independent mode many rules become consequences instead of blocks.'],
    see: ['redline', 'go-no-go'] },
  { id: 'fail-safe', cat: 'ops', title: 'Fail-safe position',
    body: ['Where a valve goes when it loses power or actuating air. Supply isolation fails closed; vents fail open; the fire valve fails closed. A system designed this way moves toward safe when anything is lost — which is also why vents must be actively held closed to pressurise.'],
    see: ['vent', 'isolation-valve'] },
  { id: 'purge', cat: 'ops', title: 'Purge',
    body: ['Flowing an inert gas (usually nitrogen or helium) through a line or chamber to remove air, moisture or propellant, or to keep hot gas and propellant out of an injector. Bipropellant engines are purged before start, often during start and shutdown, and after shutdown to clear residual propellant. A cold-gas nitrogen stand is its own purge gas and needs none.'],
    see: ['residual-propellant'] },
  { id: 'proof-test', cat: 'ops', title: 'Proof test',
    body: ['A pressure test of hardware to a level above its maximum expected operating pressure (commonly 1.5× MEOP for ground hardware), done remotely before the hardware is used, to demonstrate it holds with margin. It is done once per configuration and repeated after modification — not before every test.'],
    see: ['meop', 'leak-check'] },
  { id: 'meop', cat: 'ops', title: 'MEOP, MAWP and margins',
    body: ['Maximum expected operating pressure (MEOP) is the highest pressure the system should see in operation, including transients. Maximum allowable working pressure (MAWP) is what the weakest component is rated for. Relief is set between them. On TS-1\'s low-pressure side: MEOP 200 psig, relief 250 psig, MAWP 300 psig.'],
    see: ['relief-valve', 'proof-test'] },
  { id: 'leak-check', cat: 'ops', title: 'Leak check',
    body: ['Pressurise a section, isolate it, and watch the pressure. A falling pressure in an isolated volume is a leak — or a temperature change, so wait for the gas to settle and judge the slope, not a single reading. A regulator must be shut during the check: a regulating regulator replaces whatever leaks out and hides it. Leak checks are done first at a pressure people may be near, then (remotely) at test pressure; a leak located with snoop liquid is fixed at low pressure, never tightened under pressure.'],
    see: ['trapped-volume'] },
  { id: 'characterisation', cat: 'ops', title: 'Characterisation and test series',
    body: ['A single firing answers "what did it do?"; a characterisation answers "how does it behave?" by varying one thing — pressure, pulse width — across a planned test matrix while holding everything else fixed, then fitting the result. The fit is the product: a slope and an intercept with uncertainties, and what they say about the hardware.',
      'A series is normally run under one go/no-go poll for the approved matrix. Moving between approved points does not need a new poll; anything outside the matrix — a valve, the cell, a technician task — does. And every point starts from the same verified static condition as the first.'],
    see: ['thrust-coefficient', 'impulse-bit', 'go-no-go'] },
  { id: 'fault-isolation', cat: 'ops', title: 'Fault isolation and root cause',
    body: ['First decide whether the anomaly is in the system or in the instrument. A real change in the system shows on every channel that physics connects to it — a low chamber pressure means low thrust and low flow too. A sensor fault shows on one channel alone, and the others disagree with it. Redundant or independent measurements (a second transducer, a flowmeter against a calculated flow, a shunt calibration, a reference gauge) are how the two are told apart.',
      'Then locate before naming: "the pressure drop is between PT-201 and PT-301, and only with flow" narrows the list to what lies between two taps. Only then pick the inspection whose result would change your mind — the cheapest first. An inspection that finds nothing is evidence: it removes a suspect. A root cause names the component, the failure mode and the evidence, and says what should be done.'],
    see: ['abort', 'shunt-calibration', 'coriolis-flowmeter'] },
  { id: 'data-validity', cat: 'ops', title: 'Data validity and the test report',
    body: ['A number in a test report will be used by someone who was not there: to size a propellant load, to accept hardware, to change a design. Before it is reported, the test conductor decides whether it represents the article. Data are invalid when the stand was not as specified (a restriction, a wrong part, a regulator that could not hold its setpoint) or when an instrument in the chain was wrong (a bias, a bad calibration, a load path that bypasses the load cell). Invalid data are not deleted — they are labelled, explained, and kept, because they are evidence of what went wrong.',
      'Reduced correctly, bad data still produce clean-looking numbers. That is the danger: a reduction checks arithmetic, not truth. The checks that catch it are comparisons — against the prediction, against an independent measurement, against the last good run — and the conductor\'s willingness to write "invalid" on a test that cost a day.'],
    see: ['fault-isolation', 'characterisation', 'shunt-calibration'] },
  { id: 'go-no-go', cat: 'ops', title: 'Go / no-go poll',
    body: ['Before arming, the test conductor calls each station; each answers GO or NO-GO from its own data. The poll\'s value is the NO-GO: it is the last point at which a problem costs only time. A good poll is not a ritual — each station states the facts it is basing its call on, and any change to the configuration afterwards invalidates it.'],
    see: ['interlock', 'abort'] },
  { id: 'abort', cat: 'ops', title: 'Abort',
    body: ['Terminating a test by driving the system to a safe configuration as fast as is safe: stop the flow, isolate the supply, remove the loading, vent. Abort sequences are written in advance and executed by the controller, not improvised. After an abort, the question is always the same: was it a real system problem or an instrumentation problem? The answer determines whether the hardware can be retested.'],
    see: ['redline', 'measured-vs-true'] },

  // ---- performance
  { id: 'chamber-pressure', cat: 'perf', title: 'Chamber pressure',
    body: ['The stagnation pressure upstream of the nozzle throat. For a choked throat it sets the mass flow (ṁ = Pc·At/c*) and, with the thrust coefficient, the thrust (F = Cf·Pc·At). It is the single most informative measurement on a rocket engine: most faults show up as a chamber pressure that does not match the feed pressures that should produce it.'],
    see: ['thrust-coefficient', 'characteristic-velocity'] },
  { id: 'thrust-coefficient', cat: 'perf', title: 'Thrust coefficient (Cf)',
    body: ['Cf = F / (Pc·At): how well the nozzle turns chamber pressure into thrust. It depends on the expansion ratio, the gas, the ambient pressure (the (Pe − Pa)·Ae term), divergence loss, and whether the flow separates. Plotting F against Pc gives a straight line with a negative intercept of about −Pa·Ae — its slope and intercept are nozzle diagnostics.'],
    see: ['nozzle-expansion', 'chamber-pressure'] },
  { id: 'nozzle-expansion', cat: 'perf', title: 'Over- and under-expansion, separation',
    body: ['A nozzle expands gas to an exit pressure fixed by its area ratio and chamber pressure. If that is above ambient the nozzle is under-expanded (thrust left on the table); below ambient, over-expanded (the pressure term is negative). Far enough below — roughly 40 % of ambient — the flow separates from the wall. CGT-1\'s ratio of 2 is matched near 150 psia at sea level; at low chamber pressure it runs separated.'],
    see: ['thrust-coefficient'] },
  { id: 'characteristic-velocity', cat: 'perf', title: 'Characteristic velocity (c*)',
    body: ['c* = Pc·At / ṁ, a measure of how much chamber pressure a given mass flow produces through a given throat. For cold gas it depends only on the gas and its temperature (≈ 430 m/s for room-temperature nitrogen). For a combustion chamber it measures combustion efficiency. An apparent change in c* is a clue: either the gas, the throat, or a measurement changed.'],
    see: ['chamber-pressure', 'specific-impulse'] },
  { id: 'specific-impulse', cat: 'perf', title: 'Specific impulse (Isp)',
    body: ['Impulse per unit weight of propellant: Isp = F / (ṁ·g₀), in seconds. Nitrogen cold gas gives about 73 s in vacuum and roughly 55 s from this sea-level nozzle. Measured Isp is only as good as the thrust AND the mass flow; if mass flow is calculated from chamber pressure and an assumed throat, an eroded throat corrupts Isp while every channel looks healthy.'],
    see: ['total-impulse', 'characteristic-velocity'] },
  { id: 'total-impulse', cat: 'perf', title: 'Total impulse',
    body: ['The integral of thrust over time, ∫F dt, in N·s. Integrate baseline-corrected thrust over the whole firing including the start and shutdown transients, and check the baseline: a 0.3 N zero error integrated over 3 s is a 5 % error in a 6 N·s burn.'],
    see: ['impulse-bit', 'pressure-tare'] },
  { id: 'impulse-bit', cat: 'perf', title: 'Impulse bit',
    body: ['The total impulse delivered by one short pulse. For attitude-control thrusters it is the figure that matters: the smallest repeatable impulse bit sets how finely a spacecraft can be pointed. For very short pulses the valve never fully opens and the chamber never reaches steady state, so the impulse bit is dominated by valve timing — and its repeatability by valve-to-valve variation.'],
    see: ['solenoid-valve', 'thrust-transient'] },
  { id: 'thrust-transient', cat: 'perf', title: 'Thrust transient',
    body: ['The start and stop of thrust. At start: electrical delay in the valve coil, armature travel, chamber filling, and the thrust stand\'s own response (which rings). At stop: coil current decay to drop-out, armature return, and chamber emptying through the throat. The measured thrust transient is always the thruster convolved with the stand — read peaks with suspicion.'],
    see: ['pressure-transient', 'load-cell'] },
  { id: 'pressure-transient', cat: 'perf', title: 'Pressure transient',
    body: ['How pressures move when something changes: a chamber filling in milliseconds, a regulator outlet dipping and recovering as flow starts (droop and response), a feed line surging when a valve slams. Characterising transients — rise time, overshoot, settling — tells you about volumes, valve speeds and control stability that steady-state data cannot.'],
    see: ['thrust-transient', 'droop'] },

  // ---- biprop (Phase 6–7 content; definitions now)
  { id: 'injector-pressure-drop', cat: 'comb', title: 'Injector pressure drop',
    body: ['The difference between manifold pressure and chamber pressure across an injector, typically 15–25 % of chamber pressure. It sets the propellant flow (ṁ ≈ Cd·A·√(2ρΔP)) and isolates the feed system from chamber pressure oscillations: too little ΔP and the feed couples to the chamber (chugging); too much and the feed system must be heavier.'],
    see: ['combustion-instability', 'mixture-ratio'] },
  { id: 'mixture-ratio', cat: 'comb', title: 'Mixture ratio',
    body: ['Oxidiser mass flow divided by fuel mass flow (O/F). It sets combustion temperature and c*, and so performance and heat load. Measured from two flowmeters, or inferred from injector pressure drops; an error in either flow channel is an error in mixture ratio.',
      'For liquid oxygen and ethanol the stoichiometric ratio — just enough oxygen to burn all the fuel — is 2.08; c* peaks a little fuel-rich of it, near 1.5, because lighter products (more H₂ and CO, less H₂O and CO₂) expand faster even though they are a little cooler.'],
    see: ['injector-pressure-drop', 'equilibrium-combustion'] },
  { id: 'equilibrium-combustion', cat: 'comb', title: 'Equilibrium combustion (NASA CEA)',
    body: ['What leaves a combustion chamber, and how hot, follows from chemistry: the products settle toward chemical EQUILIBRIUM at the chamber pressure, with the propellants\' energy as heat. NASA\'s CEA program (Chemical Equilibrium with Applications, Gordon & McBride) solves for that mixture and gives the chamber temperature, the products\' molecular weight and ratio of specific heats γ, and the ideal c* — the numbers every engine designer starts from. The engines here use CEA\'s tables for liquid oxygen and ethanol.',
      'Equilibrium is an idealisation: real combustion falls a few per cent short of it (the c* efficiency), and far from stoichiometric — a fuel-rich gas generator — the chemistry is too slow to reach it at all. There CEA is run with soot and methane suppressed, and the real temperature is whatever the gas generator\'s own tests measure.'],
    see: ['characteristic-velocity', 'c-star-efficiency', 'mixture-ratio'] },
  { id: 'cryogenic-propellant', cat: 'comb', title: 'Cryogenic propellant (LOX)',
    body: ['Liquid oxygen boils at −183 °C (90 K) at one atmosphere, so in a tank it is always boiling unless it is pressurised. Heat leaks in through any insulation; in a VENTED tank it boils the liquid off and the vapour leaves through the vent — a steady loss, so the tank is filled close to the test. Shut the vent before pressurising and the boil-off pressurises the tank by itself: that is what the relief valve is for. Pressurise it with nitrogen above its vapour pressure and it is SUBCOOLED — it stops boiling and slowly warms instead.',
      'Its vapour pressure is high and steep with temperature (≈ 1 bar at 90 K, 2.5 bar at 100 K), so a LOX pump has far less suction margin than a water or fuel pump at the same tank pressure — and the pump\'s own heat eats into it. Oxygen-enriched air near a leak turns grease, clothing and asphalt into fuel: everything that touches oxygen is cleaned for oxygen service.'],
    see: ['npsh', 'ullage', 'relief-valve'] },
  { id: 'hard-start', cat: 'comb', title: 'Hard start',
    body: ['An ignition that happens after too much propellant has accumulated in the chamber, so it burns almost at once and produces a pressure spike far above normal chamber pressure. Causes: late ignition, a valve leading the igniter, a failed igniter. Prevention: ignition confirmation before main-valve opening, and careful valve sequencing.'],
    see: ['combustion-instability', 'ignition', 'start-transient'] },
  { id: 'combustion-instability', cat: 'comb', title: 'Combustion instability',
    body: ['Self-sustaining pressure oscillations in a combustion chamber: low-frequency "chugging" coupled to the feed system, or high-frequency acoustic modes of the chamber that can destroy an injector in milliseconds. Seen as growing oscillation on a high-response chamber-pressure channel — which is why that channel is sampled fast and why an oscillation redline exists.'],
    see: ['injector-pressure-drop', 'injector-stiffness'] },
  { id: 'residual-propellant', cat: 'comb', title: 'Residual propellant',
    body: ['Propellant left in manifolds and injector passages after main-valve closure. It can burn or dribble after shutdown (an afterburn visible on chamber pressure) and must be purged before the hardware is approached.'],
    see: ['purge'] },
  { id: 'pressure-fed', cat: 'fluid', title: 'Pressure-fed feed system',
    body: ['Propellant is pushed from its tank by gas pressure alone — no pump. Simple and reliable, at the cost of heavy tanks (they must hold more than the chamber pressure, plus every pressure drop between them and the injector). The tank pressure IS the feed pressure, so the pressurant regulator is the throttle and its droop is a flow error at the engine.',
      'Budget: P_tank = P_c + ΔP_injector + ΔP_lines + ΔP_valves. Every term is something a test measures.'],
    see: ['ullage', 'regulator', 'injector'] },
  { id: 'ullage', cat: 'fluid', title: 'Ullage',
    body: ['The gas space above the liquid in a tank. As liquid leaves, the ullage grows, its gas expands and cools, and the pressurant regulator has to keep filling it to hold the pressure. A tank run nearly dry has a large, cold ullage; a tank run fully dry ingests gas into the feed line, and the flow — and the run — collapses.'],
    see: ['pressure-fed', 'blowdown'] },
  { id: 'injector', cat: 'comb', title: 'Injector and its flow coefficient (CdA)',
    body: ['The injector meters each propellant into the chamber through many small orifices. Its behaviour is captured by one number per side, CdA: ṁ = CdA·√(2ρ·ΔP). The drawing gives an estimate — hole area times an assumed discharge coefficient — but burrs, edge radii and manufacturing scatter mean the real value is only known by flowing it.',
      'Because ṁ scales with √ρ at a given ΔP, a water cold flow predicts the propellant flows directly: same CdA, propellant density. The mixture ratio the engine will run at follows from the two sides\' CdA values before any propellant is loaded.'],
    see: ['cold-flow', 'mixture-ratio', 'injector-pressure-drop'] },
  { id: 'cold-flow', cat: 'ops', title: 'Cold flow',
    body: ['Flowing an inert simulant (usually water, sometimes the real propellant without ignition) through the feed system and injector. It measures what the drawing could only estimate: line losses, priming time, each injector side\'s flow coefficient, flowmeter calibration against a weigh scale, and how the valves and manifolds behave in transients. It is also the first full run of the procedure, the sequencer and the abort logic with nothing that can burn.',
      'Every result is converted to the real propellants by density. Get the cold flow wrong and the hot fire runs at the wrong mixture ratio.'],
    see: ['injector', 'priming', 'water-hammer'] },
  { id: 'priming', cat: 'fluid', title: 'Priming',
    body: ['The time between a main valve opening and liquid reaching — and filling — the injector. Until the manifold is full, what comes out of the orifices is purge gas or air, then a mixture, then liquid. In a hot fire the two sides prime at different times, and the start sequence (which valve opens first, the "lead", and when the igniter fires) is built around them: too much of one propellant in the chamber before the other arrives is how hard starts happen.'],
    see: ['cold-flow', 'purge', 'hard-start'] },
  { id: 'water-hammer', cat: 'fluid', title: 'Water hammer',
    body: ['A moving liquid column has momentum. Stop it by closing a valve and the column decelerates against the valve, raising the pressure upstream of it — briefly, sometimes far above the tank pressure. The faster the valve closes and the longer the line, the bigger the surge (here a lumped approximation of what is really a pressure wave travelling at the speed of sound in the liquid). Main-valve closing times are chosen as much for the hammer as for the shutdown transient.'],
    see: ['cold-flow'] },
  { id: 'ignition', cat: 'comb', title: 'Ignition and ignition confirmation',
    body: ['Non-hypergolic propellants need an ignition source: here a spark igniter, energised before the propellants arrive so that the first mixture to reach it lights. The time from both propellants arriving to flame is the ignition delay; the time from the later main valve command to flame (priming plus delay) is what the data show.',
      'Ignition is CONFIRMED, never assumed: chamber pressure above a threshold by a set time (the ignition check), backed by a flame detector. No confirmation means unburned propellant is entering the chamber, and the sequence must stop the flow and purge. Exciter current proves the exciter, not the spark — someone must have seen it spark.'],
    see: ['hard-start', 'priming'] },
  { id: 'heat-sink-chamber', cat: 'comb', title: 'Heat-sink (uncooled) chamber',
    body: ['A thick copper chamber with no coolant: the walls simply absorb the heat of a short burn. Cheap, robust and ideal for development testing — and limited in duration, because the throat (the highest heat flux) warms continuously until it reaches its temperature limit. The burn-time limit is a thermal budget.',
      'After shutdown the heat in the hot inner wall keeps conducting outward, so embedded thermocouples go on rising for seconds: soak-back. The peak after the run, not the reading at shutdown, is the one to compare with the limit — and the chamber must cool before it is fired again.'],
    see: ['film-cooling'] },
  { id: 'film-cooling', cat: 'comb', title: 'Film cooling',
    body: ['A ring of small fuel orifices around the injector edge lays a fuel-rich, cooler layer along the chamber wall. It costs a little performance (that fuel burns poorly) and saves the wall a great deal of heat. Block some of those holes and the engine performs exactly as before while the wall heats much faster — a fault that only the wall thermocouples see.'],
    see: ['heat-sink-chamber'] },
  { id: 'c-star-efficiency', cat: 'perf', title: 'c* efficiency',
    body: ['Measured c* (= Pc·At/ṁ) divided by the ideal c* for the measured mixture ratio. It is the cleanest single figure for how well an injector mixes and burns its propellants — 0.90–0.98 is typical of a good small engine. Because it combines chamber pressure, throat area and BOTH flows, an error in any of those measurements moves it: a "better than ever" c* is first a reason to check the instruments.'],
    see: ['characteristic-velocity', 'mixture-ratio'] },
  { id: 'injector-stiffness', cat: 'comb', title: 'Injector stiffness and chug',
    body: ['The injector pressure drop as a fraction of chamber pressure. A stiff injector (ΔP/Pc of 0.2 or more) isolates the feed from the chamber; a soft one lets a chamber-pressure dip increase the flow, which raises the pressure, which reduces the flow — a low-frequency oscillation called chug, at tens to a few hundred hertz.',
      'Because injector ΔP falls as the square of flow and chamber pressure only in proportion to it, a pressure-fed engine gets softer as it is throttled down: run it at too low a tank pressure and it chugs. Here chug is a lumped onset criterion with a growing oscillation, not a solution of the feed-system dynamics.'],
    see: ['combustion-instability', 'injector-pressure-drop'] },
  { id: 'start-transient', cat: 'comb', title: 'Start transient and lead',
    body: ['The first fraction of a second of a hot fire: valves open, manifolds prime, the igniter lights the first mixture, chamber pressure rises and overshoots, the flows throttle back to steady state. A zero-lead start (both valves together) with the igniter already sparking is smooth on this engine. Lead one propellant by tens of milliseconds and it collects in the chamber; lead it by a hundred and it is a hard start.',
      'Read a start by its valve-to-flame time, its rise time and its overshoot. Track them run to run: a start getting later or rougher is an igniter or a valve wearing out.'],
    see: ['hard-start', 'priming', 'ignition'] },
  { id: 'dribble-volume', cat: 'comb', title: 'Dribble volume and shutdown impulse',
    body: ['The propellant between the main valve and the injector face. At shutdown it does not stop when the valve does: the purge pushes it out and it burns, poorly, for a few tenths of a second. The impulse delivered after the valve command is the shutdown impulse — for a small engine with large manifolds a sizeable fraction of a short burn, which is why pulse engines put their valves right on the injector.'],
    see: ['residual-propellant', 'purge'] },
  { id: 'regenerative-cooling', cat: 'comb', title: 'Regenerative cooling',
    body: ['One propellant — here the fuel — flows through channels in the chamber wall before it reaches the injector, and carries away the heat the hot gas puts into the wall. The heat is not lost: it goes back into the chamber with the propellant, hence "regenerative". The wall is a thin, conductive liner; its temperature is set by the balance between the gas-side heat transfer (highest at the throat) and the coolant-side heat transfer (set by the coolant\'s velocity and state).',
      'It removes the heat-sink chamber\'s burn-time limit and replaces it with others: the coolant must not boil at the wall, must not coke, and must have enough pressure left after the jacket\'s pressure drop to feed the injector. All three get worse as the engine is throttled down or run with less fuel — the coolant flow falls faster than the heat load.'],
    see: ['critical-heat-flux', 'coking', 'heat-sink-chamber'] },
  { id: 'critical-heat-flux', cat: 'comb', title: 'Boiling and critical heat flux',
    body: ['A liquid coolant against a hot wall first carries heat by forced convection. If the wall passes the liquid\'s saturation temperature (which depends on the local pressure) bubbles form and help — nucleate boiling. Push the heat flux past the CRITICAL HEAT FLUX and the bubbles merge into a vapour film; vapour is a poor conductor, the coefficient collapses, and the wall temperature jumps by hundreds of kelvin in a fraction of a second. That is burnout, and on a 1 mm liner it is a hole.',
      'Critical heat flux rises with coolant velocity and with subcooling (how far the bulk coolant is below saturation). So the margin shrinks with less flow, hotter coolant, or lower jacket pressure. The film, once formed, does not go away until the wall cools. Here this is a lumped criterion per wall zone with invented constants.'],
    see: ['regenerative-cooling'] },
  { id: 'coking', cat: 'comb', title: 'Coking',
    body: ['Hydrocarbon and alcohol fuels decompose on a hot wall and leave a carbonaceous deposit on the coolant side of the channels. The deposit is a thermal insulator: the liner runs hotter for the same heat flux, and the coolant picks up a little less heat — the wall temperature trend goes up while the coolant outlet temperature goes down. It grows faster the hotter the wall, so it feeds itself, and it stays from run to run.'],
    see: ['regenerative-cooling', 'critical-heat-flux'] },
  // ---- turbomachinery
  { id: 'centrifugal-pump', cat: 'turbo', title: 'Centrifugal pump and head',
    body: ['An impeller flings the liquid outward and a volute collects it at higher pressure. What a pump adds is HEAD — energy per unit weight of liquid, a height in metres — not pressure: the pressure rise is ρ·g·H, so the same impeller at the same speed gives more pressure on a dense liquid and less on a light one. TPA-1\'s oxidiser pump makes 390 m: on LOX (1141 kg/m³) that is 4.4 MPa, on water 3.8 MPa.',
      'At a fixed speed the head falls as the flow rises — the pump\'s head–flow curve — from the SHUTOFF head at zero flow to nothing at "runout". Where on that curve the pump runs is decided by what it feeds: here the throttle valve, on an engine the injector. The shaft power a radial pump draws at zero flow is still a large fraction of its design power, and all of it goes into the liquid trapped in the casing.'],
    see: ['affinity-laws', 'pump-map', 'npsh', 'deadhead'] },
  { id: 'affinity-laws', cat: 'turbo', title: 'Affinity laws',
    body: ['For one pump at different speeds, operating at the same FLOW COEFFICIENT (flow divided by speed): flow ∝ speed, head ∝ speed², power ∝ speed³. Double the speed and you get twice the flow, four times the head, eight times the power.',
      'Test data are referred to the design speed with them: H/n² against Q/n, n = N / N_design. Points taken at slightly different speeds — or whole maps at different speeds — should then fall on one curve. Where they do not, the pump is not obeying similarity, and the usual reason is cavitation at the high-flow, low-suction end. Pump head is also a speedometer in its own right: a head that is 17 % high says the shaft ran 8 % fast.'],
    see: ['centrifugal-pump', 'pump-map'] },
  { id: 'pump-map', cat: 'turbo', title: 'Pump map',
    body: ['The head–flow curve (and efficiency) measured on a test stand by holding the speed and walking the throttle through a set of positions, one steady point each — or several runs at different speeds, referred to design speed. It is the pump\'s acceptance data and the reference every later test is compared against: a curve that has moved down by a constant fraction is internal leakage (worn wear rings); one that drops off at high flow is cavitation.'],
    see: ['affinity-laws', 'npsh'] },
  { id: 'npsh', cat: 'turbo', title: 'NPSH — net positive suction head',
    body: ['The margin, in metres of liquid, between the pressure at the pump inlet and the liquid\'s vapour pressure: NPSHa = (P_inlet − P_vapour) / (ρ·g). If the pressure at the impeller eye falls to the vapour pressure, the liquid boils there (cavitation): vapour bubbles take up passage area, the head falls, and the bubbles collapse further in, eroding the blades.',
      'Every pump has an NPSH REQUIRED, which rises roughly with the square of the speed and with flow. By definition it is the suction head at which the head has fallen 3 % — measured by a suction test: hold speed and flow, lower the inlet pressure steadily, and watch the head hold, then break. An inducer (a helical first stage) is what lets rocket pumps run on low tank pressures. Running near NPSHr costs vibration; below it, the pump unloads and the turbine overspeeds.'],
    see: ['centrifugal-pump', 'overspeed'] },
  { id: 'turbine', cat: 'turbo', title: 'Impulse turbine',
    body: ['Gas expands through nozzles to a high SPOUTING velocity c0 = √(2·cp·T·(1 − (p_exit/p_inlet)^((γ−1)/γ))) and turns on a row of blades. The torque is largest with the rotor stalled and falls to zero when the blade speed u catches up with the jet; efficiency peaks at a blade-to-spouting-velocity ratio u/c0 around 0.4–0.5. Partial admission (nozzles round only part of the disc), tip leakage and windage take a share.',
      'On a cold-gas spin rig the efficiency is measured with no torque meter at all: the gas leaves colder by exactly the work it did, so η = (T_inlet − T_exhaust) / ΔT_isentropic. Cold nitrogen at 230 psig leaves TPA-1\'s turbine at about −75 °C.'],
    see: ['speed-control', 'overspeed'] },
  { id: 'speed-control', cat: 'turbo', title: 'Speed control',
    body: ['TS-3 holds the shaft speed with a closed loop: the speed controller SC-330 compares the speed pickups with the planned speed and moves the turbine drive pressure (through EPC-330). It starts from a FEED-FORWARD — the drive pressure the prediction says the speed needs — and corrects the rest with proportional and integral action; the integrator is held while the speed is still ramping, so it does not wind up on the lag and overshoot at the top.',
      'A closed loop hides faults inside its own output: the speed is perfect, so look at what the controller had to DO. A blocked turbine nozzle shows up as a drive pressure far above the feed-forward. And the loop trusts its feedback completely: a speed pickup that reads low drives the real shaft fast.'],
    see: ['turbine', 'overspeed'] },
  { id: 'overspeed', cat: 'turbo', title: 'Overspeed and the speed redline',
    body: ['A turbopump\'s rotor stores tens of kilojoules and is a few per cent from bursting at its design speed. Anything that takes the load off while the turbine is still driven — a pump that loses its suction (cavitation, an empty tank, gas in the line), a discharge valve that shuts, a speed pickup that lies to the controller — lets the shaft accelerate by thousands of rpm per second.',
      'The redline (here 110 % of design) is on the HIGHER of two speed pickups, so a pickup that fails low cannot hide an overspeed; a pickup that fails high aborts a good run instead — the cheaper mistake. Even so the turbine start valve takes tens of milliseconds to shut, and the shaft overshoots the redline before it slows: that margin is why a redline is set well below the speed at which the rotor would fail.'],
    see: ['speed-control', 'npsh', 'deadhead'] },
  { id: 'deadhead', cat: 'turbo', title: 'Deadheading',
    body: ['Running a pump against a closed discharge. No flow, so no hydraulic power delivered — but the pump still draws a large share of its design power, and all of it heats the few hundred grams of liquid trapped in the casing: tens of degrees a minute, towards boiling at the inducer. On a turbopump the shaft also loses most of its load and speeds up. The discharge valves are opened before the turbine starts and shut only after the rotor has coasted down.'],
    see: ['centrifugal-pump', 'overspeed'] },
  { id: 'relieving-regulator', cat: 'turbo', title: 'Relieving regulator',
    body: ['A regulator with a relief port on its outlet: it can bring the pressure DOWN to a new, lower setpoint by bleeding the excess, not only up. TS-3\'s tank regulators are relieving, which is what lets a suction test ramp the tank pressure down under a running pump. It also means a relieving regulator set to zero vents its tank — which a leak check has to allow for.'],
    see: ['npsh'] },
  // ---- the gas-generator engine
  { id: 'pump-fed', cat: 'turbo', title: 'Pump-fed feed system',
    body: ['The tanks only have to keep the pumps out of cavitation — tens of psi, not hundreds — and the pumps make the pressure the injector needs. Thin, light tanks are the whole point: on a large vehicle the turbopump weighs far less than the tank wall it saves. The price is a machine that must be started, can stall or run away, and turns the engine into a closed loop.',
      'On a pump-fed engine the tank pressure is not the throttle. The power delivered to the pumps is — which on a gas-generator engine means the gas generator.'],
    see: ['pressure-fed', 'npsh', 'gas-generator-cycle'] },
  { id: 'gas-generator-cycle', cat: 'turbo', title: 'Gas-generator cycle',
    body: ['A small fraction of the propellant — here about 4 % — is burned in a separate GAS GENERATOR, far from the best mixture ratio so that its gas is cool enough for an uncooled turbine (here very fuel-rich, about 850 K). The gas drives the turbine and is then thrown away: through an exhaust duct, or into the nozzle\'s skirt. The main chamber gets the rest.',
      'It is the simplest pump-fed cycle to develop, because the turbine and the main chamber are only loosely coupled. Its cost is that thrown-away flow: it makes almost no thrust, so the engine\'s specific impulse sits below the main chamber\'s by roughly the gas generator\'s share. Staged-combustion cycles burn that gas again in the main chamber and recover it — at the price of turbine inlet pressures several times the chamber\'s.'],
    see: ['bootstrap', 'turbine-inlet-temperature', 'throttling', 'turbine'] },
  { id: 'bootstrap', cat: 'turbo', title: 'Bootstrap start',
    body: ['A gas-generator engine cannot start itself: no pump pressure, no gas generator flow, no turbine power. Something spins the turbine first — here nitrogen START GAS from PR-330 through TSV-332; on flight engines a start cartridge, a spin tank, or tank head alone. Once the pumps make enough pressure the main chamber and the gas generator light, and when the gas generator\'s power exceeds what the shaft needs at that speed, the start gas is shut and the engine accelerates on its own to mainstage. It has bootstrapped.',
      'Two ways to get it wrong. Too little start energy (low start pressure, or shut too early) and the gas generator never catches up: the speed sags and settles short of mainstage — a START HANG, which the speed check at T+2.5 s catches. Too much (high pressure, or left on too long) and the turbine has two drives while the pumps are still lightly loaded: OVERSPEED. Every gas-generator start sequence is tuned on a test stand.'],
    see: ['gas-generator-cycle', 'overspeed', 'start-transient'] },
  { id: 'turbine-inlet-temperature', cat: 'turbo', title: 'Turbine inlet temperature (TIT)',
    body: ['The temperature of the gas generator\'s gas entering the turbine — the redline of a gas-generator engine, because the turbine blades are uncooled and lose strength fast above a thousand kelvin or so. It is set by the gas generator\'s MIXTURE RATIO: fuel-rich, the flame is cooled by the excess fuel. For LOX and ethanol the equilibrium chemistry makes that curve flat over the usual range — about 35 K per 0.1 of mixture ratio between 0.3 and 0.5 — and then steep, past about 0.55, where the free hydrocarbons are used up: the redline guards that knee. So here a gas generator given more oxidiser (an eroded orifice) runs a little hotter but, above all, passes more gas and speeds the engine up; one starved of fuel (a blocked orifice) runs a little hotter and passes LESS gas, so the engine slows. (Real fuel-rich gas generators are kinetically limited; their temperature against mixture ratio is measured, not computed.)',
      'The gas generator\'s flows are too small for turbine meters, so they are INFERRED from the pressure drop across calibrated orifices. That inference assumes the orifices are what the drawing says; an eroded orifice makes the inferred mixture ratio look right while the TIT says otherwise. Here TT-334 is a bare-bead thermocouple: fast, and fragile.'],
    see: ['gas-generator-cycle', 'mixture-ratio', 'thermocouple'] },
  { id: 'throttling', cat: 'turbo', title: 'Throttling a pump-fed engine',
    body: ['A gas-generator engine throttles by cutting the gas generator\'s flow: less turbine power, a slower shaft, less pump pressure, less propellant through the main injector, lower chamber pressure and thrust. Move both gas generator legs together and its mixture ratio — so the turbine inlet temperature — stays put; move one and the TIT moves instead of the thrust.',
      'The floor is usually the INJECTOR. Its pressure drop goes as the square of the flow while the chamber pressure goes as the flow, so the stiffness ΔP/Pc falls in proportion to thrust. Below about 15–20 % stiffness the chamber starts to talk back to the feed system and the engine chugs. The pumps also leave their best-efficiency flow, and their inducers their best suction margin.'],
    see: ['injector-stiffness', 'combustion-instability', 'gas-generator-cycle'] },
  { id: 'ablative-chamber', cat: 'comb', title: 'Ablative chamber',
    body: ['A chamber lined with a fibre-reinforced resin (here silica-phenolic) that is consumed as it protects the case behind it. Heated from the inside, the resin pyrolyses into a porous CHAR; the gases from the pyrolysis percolate out through the char and cool it, and the char itself insulates. The hot face recedes a fraction of a millimetre a second. No coolant, no plumbing, no limit from heat soak — only a limit on how much liner there is.',
      'At the throat the char also ERODES, so the throat grows through the burn and the chamber pressure drifts down at constant flow: a long burn shows it as a slow sag in Pc. The case thermocouple sees the burn late — the liner is an insulator — and keeps rising after shutdown as the stored heat soaks outward. Here: a 14 mm liner, about 0.15 mm/s of char at full pressure, a 60 s design burn. The model is a one-dimensional char front with a fixed rate law; real ablatives char unevenly and spall.'],
    see: ['heat-sink-chamber', 'regenerative-cooling', 'characteristic-velocity'] },
];
