/* Headless validation of the ephemeris against JPL Horizons.
   The fixture in data/fixtures/horizons.json was generated by
   tools/horizons_fixture.py with an observer standing on the lunar surface
   (CENTER='coord@301', APPARENT='AIRLESS'): 10 sites, 12 epochs, Sun and Earth. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ephemerisAt, skyAt, jdFromUnixMs, moonOrientation, greenwichMeanSiderealTime,
         localSolarTime } from '../src/physics/ephemeris.js';
import { azEl, surfaceDistance, bearing, offsetLatLon, horizonDistance,
         gravityMagnitude, llhToXyz, xyzToLlh, enuBasis, dot } from '../src/physics/frames.js';
import { R_MOON } from '../src/config.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(fs.readFileSync(path.join(here, '..', 'data', 'fixtures', 'horizons.json'), 'utf8'));

let failures = 0;
const check = (label, cond, detail = '') => {
  console.log((cond ? '  ok   ' : '  FAIL ') + label + (detail ? '  — ' + detail : ''));
  if (!cond) failures++;
};
const angDiff = (a, b) => { let d = Math.abs(a - b) % 360; return d > 180 ? 360 - d : d; };

/* ---- frames ---- */
{
  console.log('frames');
  const rt = xyzToLlh(...Object.values(llhToXyz(23.5, -47.4, 1234)));
  check('lat/lon/height round trip',
    Math.abs(rt.lat - 23.5) < 1e-9 && Math.abs(rt.lon + 47.4) < 1e-9 && Math.abs(rt.h - 1234) < 1e-6);

  const b = enuBasis(12.3, 45.6);
  check('ENU basis orthonormal',
    Math.abs(dot(b.e, b.n)) < 1e-12 && Math.abs(dot(b.e, b.u)) < 1e-12 &&
    Math.abs(dot(b.n, b.u)) < 1e-12 && Math.abs(dot(b.u, b.u) - 1) < 1e-12);

  // Apollo 11 to Apollo 17, a real distance a rover journey would have to cover.
  const d = surfaceDistance(0.67415, 23.47314, 20.19108, 30.77220) / 1000;
  check('Apollo 11 to Apollo 17 is ~640 km', d > 600 && d < 680, d.toFixed(1) + ' km');

  const off = offsetLatLon(0, 0, 90, 100000);
  check('100 km due east of (0,0) lands on the equator',
    Math.abs(off.lat) < 1e-9 && Math.abs(off.lon - 3.2977) < 0.001, off.lon.toFixed(4) + ' deg');
  check('bearing back is due west', Math.abs(bearing(off.lat, off.lon, 0, 0) - 270) < 1e-6);

  const hz = horizonDistance(1.62);
  check('horizon at eye height is ~2.4 km', hz > 2300 && hz < 2400, (hz / 1000).toFixed(2) + ' km');
  check('surface gravity is 1.62 m/s^2', Math.abs(gravityMagnitude(R_MOON) - 1.6246) < 0.002,
    gravityMagnitude(R_MOON).toFixed(4));
}

/* ---- orientation ---- */
{
  console.log('lunar orientation (IAU/WGCCRE)');
  const M = moonOrientation(2451545.0).bodyFromJ2000;
  let orthonormal = true;
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      const d = M[i * 3] * M[j * 3] + M[i * 3 + 1] * M[j * 3 + 1] + M[i * 3 + 2] * M[j * 3 + 2];
      if (Math.abs(d - (i === j ? 1 : 0)) > 1e-12) orthonormal = false;
    }
  }
  check('body-from-J2000 matrix is orthonormal', orthonormal);

  const g = greenwichMeanSiderealTime(2451545.0);
  check('GMST at J2000 is 280.46 deg', Math.abs(g - 280.46) < 0.01, g.toFixed(3));
}

/* ---- against Horizons ---- */
console.log('vs JPL Horizons (' + Object.keys(fixture.epochs).length + ' epochs x ' +
            Object.keys(fixture.sites).length + ' sites)');
const worst = { sunAz: 0, sunEl: 0, earthAz: 0, earthEl: 0, illum: 0, angdiam: 0,
                subELon: 0, subELat: 0, subSLon: 0, subSLat: 0,
                earthSubLon: 0, earthSubLat: 0 };
let n = 0, sunElBias = 0;
for (const [epoch, data] of Object.entries(fixture.epochs)) {
  const jd = jdFromUnixMs(Date.parse(epoch.replace(' ', 'T') + ':00Z'));
  const eph = ephemerisAt(jd);

  worst.subELon = Math.max(worst.subELon, angDiff(eph.subEarth.lon, data.subpoints.subearth_lon));
  worst.subELat = Math.max(worst.subELat, Math.abs(eph.subEarth.lat - data.subpoints.subearth_lat));
  worst.subSLon = Math.max(worst.subSLon, angDiff(eph.subSolar.lon, data.subpoints.subsolar_lon));
  worst.subSLat = Math.max(worst.subSLat, Math.abs(eph.subSolar.lat - data.subpoints.subsolar_lat));

  /* The other sub-point: which spot on Earth is under the Moon, and therefore
     which continents are facing anyone standing on the near side. Horizons
     reports it per observing site, but it barely moves across the Moon, so one
     site is enough to pin it down. Cosine-weighted because longitude means
     little near a pole. */
  {
    const t = data.sites.tranquility.earth;
    if (t.sub_lon !== undefined) {
      const w = Math.cos(t.sub_lat * Math.PI / 180);
      worst.earthSubLon = Math.max(worst.earthSubLon,
        angDiff(eph.earthSubLon, t.sub_lon) * w);
      worst.earthSubLat = Math.max(worst.earthSubLat, Math.abs(eph.earthSubLat - t.sub_lat));
    }
  }

  for (const [name, site] of Object.entries(fixture.sites)) {
    const sky = skyAt(eph, site.lat, site.lon, 0);
    const t = data.sites[name];
    // Azimuth is meaningless when something is straight overhead, so weight the
    // azimuth error by the cosine of the elevation.
    const wSun = Math.cos(sky.sunEl * Math.PI / 180);
    const wEarth = Math.cos(sky.earthEl * Math.PI / 180);
    worst.sunAz = Math.max(worst.sunAz, angDiff(sky.sunAz, t.sun.az) * wSun);
    worst.sunEl = Math.max(worst.sunEl, Math.abs(sky.sunEl - t.sun.el));
    worst.earthAz = Math.max(worst.earthAz, angDiff(sky.earthAz, t.earth.az) * wEarth);
    worst.earthEl = Math.max(worst.earthEl, Math.abs(sky.earthEl - t.earth.el));
    worst.illum = Math.max(worst.illum, Math.abs(sky.earthIllum * 100 - t.earth.illum));
    worst.angdiam = Math.max(worst.angdiam,
      Math.abs(sky.earthAngularRadius * 2 * 3600 - t.earth.angdiam_arcsec));
    sunElBias += sky.sunEl - t.sun.el;
    n++;
  }
}
check('Sun elevation within 0.05 deg', worst.sunEl < 0.05, worst.sunEl.toFixed(4) + ' deg worst');
check('Sun azimuth within 0.05 deg', worst.sunAz < 0.05, worst.sunAz.toFixed(4) + ' deg worst');
check('Earth elevation within 0.05 deg', worst.earthEl < 0.05, worst.earthEl.toFixed(4) + ' deg worst');
check('Earth azimuth within 0.05 deg', worst.earthAz < 0.05, worst.earthAz.toFixed(4) + ' deg worst');
check('Earth illuminated fraction within 1 %', worst.illum < 1.0, worst.illum.toFixed(3) + ' % worst');
check('Earth angular diameter within 5 arcsec', worst.angdiam < 5, worst.angdiam.toFixed(1) + '" worst');
check('the right face of the Earth is turned towards the Moon, within 0.5 deg',
  worst.earthSubLon < 0.5 && worst.earthSubLat < 0.5,
  `lon ${worst.earthSubLon.toFixed(3)} lat ${worst.earthSubLat.toFixed(3)}`);
check('sub-Earth point within 0.05 deg',
  worst.subELon < 0.05 && worst.subELat < 0.05,
  `lon ${worst.subELon.toFixed(3)} lat ${worst.subELat.toFixed(3)}`);
check('sub-solar point within 0.05 deg',
  worst.subSLon < 0.05 && worst.subSLat < 0.05,
  `lon ${worst.subSLon.toFixed(3)} lat ${worst.subSLat.toFixed(3)}`);
console.log(`         (${n} comparisons, mean Sun elevation bias ${(sunElBias / n).toFixed(4)} deg)`);

/* ---- the moments that matter ---- */
{
  console.log('landmark checks');
  const jd11 = jdFromUnixMs(Date.parse('1969-07-20T20:17:00Z'));
  const e11 = ephemerisAt(jd11);
  const tb = skyAt(e11, 0.67415, 23.47314);
  check('Apollo 11 landing: Sun 10.7 deg above the eastern horizon',
    Math.abs(tb.sunEl - 10.70) < 0.05 && Math.abs(tb.sunAz - 88.81) < 0.05,
    `az ${tb.sunAz.toFixed(2)} el ${tb.sunEl.toFixed(2)}`);
  check('Apollo 11 landing: Earth high in the west, ~67 % lit',
    tb.earthEl > 55 && tb.earthEl < 63 && Math.abs(tb.earthIllum - 0.672) < 0.01,
    `el ${tb.earthEl.toFixed(1)} illum ${(tb.earthIllum * 100).toFixed(1)}%`);
  check('Apollo 11 landing: long shadows (Sun below 15 deg)', tb.sunEl < 15);

  // The far side never sees the Earth, all year, from anywhere well past the limb.
  let farsideMax = -90;
  for (let d = 0; d < 365; d += 3) {
    const e = ephemerisAt(jdFromUnixMs(Date.UTC(2026, 0, 1) + d * 86400000));
    farsideMax = Math.max(farsideMax, skyAt(e, -45.4446, 177.5991).earthEl);
  }
  check('Chang\'e 4 site never sees the Earth in a year', farsideMax < 0,
    'highest ' + farsideMax.toFixed(1) + ' deg');

  // Libration: over a year the sub-Earth point wanders by several degrees, which
  // is why 59 % of the surface is visible from Earth rather than 50 %.
  let lonMin = 999, lonMax = -999, latMin = 999, latMax = -999;
  for (let d = 0; d < 400; d += 1) {
    const e = ephemerisAt(jdFromUnixMs(Date.UTC(2026, 0, 1) + d * 86400000));
    lonMin = Math.min(lonMin, e.subEarth.lon); lonMax = Math.max(lonMax, e.subEarth.lon);
    latMin = Math.min(latMin, e.subEarth.lat); latMax = Math.max(latMax, e.subEarth.lat);
  }
  check('libration in longitude reaches 5-9 deg each way',
    lonMax > 5 && lonMax < 9 && lonMin < -5 && lonMin > -9,
    `${lonMin.toFixed(2)} .. ${lonMax.toFixed(2)}`);
  check('libration in latitude reaches 5-7 deg each way',
    latMax > 5 && latMax < 7.5 && latMin < -5 && latMin > -7.5,
    `${latMin.toFixed(2)} .. ${latMax.toFixed(2)}`);

  // The sub-solar latitude is the Moon's season: tiny, because its axis is
  // almost upright to the ecliptic.
  let decMax = 0;
  for (let d = 0; d < 400; d += 1) {
    decMax = Math.max(decMax, Math.abs(ephemerisAt(jdFromUnixMs(Date.UTC(2026, 0, 1) + d * 86400000)).subSolar.lat));
  }
  check('sub-solar latitude stays within 1.6 deg', decMax < 1.7, decMax.toFixed(3) + ' deg');

  // A lunar day is a synodic month: 29.53 Earth days from noon to noon.
  const e0 = ephemerisAt(jdFromUnixMs(Date.UTC(2026, 3, 1)));
  const t0 = localSolarTime(e0, 0, 23.47);
  let wrapDays = 0;
  for (let d = 1; d < 40; d += 0.05) {
    const t = localSolarTime(ephemerisAt(jdFromUnixMs(Date.UTC(2026, 3, 1) + d * 86400000)), 0, 23.47);
    if (d > 25 && Math.abs(t - t0) < 0.002) { wrapDays = d; break; }
  }
  check('a lunar day lasts 29.5 Earth days', Math.abs(wrapDays - 29.53) < 0.6,
    wrapDays.toFixed(2) + ' days');

  // Sun and Earth angular sizes as seen from the surface.
  const now = ephemerisAt(jdFromUnixMs(Date.UTC(2026, 8, 8)));
  check('Sun is about half a degree across',
    now.sunAngularRadius * 2 > 0.52 && now.sunAngularRadius * 2 < 0.55,
    (now.sunAngularRadius * 2).toFixed(4) + ' deg');
  check('Earth is about two degrees across',
    now.earthAngularRadius * 2 > 1.75 && now.earthAngularRadius * 2 < 2.05,
    (now.earthAngularRadius * 2).toFixed(4) + ' deg');
  check('Earth is roughly 3.7 times wider than the Sun',
    now.earthAngularRadius / now.sunAngularRadius > 3.2 &&
    now.earthAngularRadius / now.sunAngularRadius < 4.0,
    (now.earthAngularRadius / now.sunAngularRadius).toFixed(2) + 'x');

  // Standing at the sub-Earth point puts the Earth straight overhead.
  const sub = skyAt(now, now.subEarth.lat, now.subEarth.lon);
  check('Earth is overhead at the sub-Earth point', sub.earthEl > 89.0,
    sub.earthEl.toFixed(2) + ' deg');
}

console.log(failures === 0 ? '\nephemeris: all checks passed' : `\nephemeris: ${failures} FAILED`);
process.exit(failures ? 1 : 0);
